// gaps-overlay.ts — §8 ?debug=gaps instrument: invented-trace overlay.
//
// The resampled route (route.line drawn by route-line.ts) is a uniform 5 m
// walk, so a resampled point with along-track distance d is invented iff d
// falls inside one of the raw-GPX gap intervals (GAP_RANGES, generated by
// scripts/18-audit-gpx.ts over the ORIGINAL track, pre-resample).
//
// Lazy chunk (imported only when ?debug=gaps): a per-segment Line2 in
// magenta (0xff00ff — absent from the palette) using the SAME drape as the
// normal line (copies of its world positions), with the same progressive
// cut semantics? No — the overlay draws the WHOLE invented stretch always:
// it answers "how much trace is invented and where", not "what is walked".
// renderOrder 7 (above solid 6), depthTest on so terrain occludes honestly.
//
// Never writes a state the piece drives: no uniforms, no progress, no LOD.
import * as THREE from "three";
import { Line2 } from "three/addons/lines/Line2.js";
import { LineGeometry } from "three/addons/lines/LineGeometry.js";
import { LineMaterial } from "three/addons/lines/LineMaterial.js";
import type { RouteData } from "./telemetry.ts";

const MAGENTA = 0xff00ff;

function inventedAt(d: number, ranges: Array<readonly [number, number]>): boolean {
  for (const [lo, hi] of ranges) {
    if (d >= (lo as number) && d <= (hi as number)) return true;
  }
  return false;
}

/** Build one Line2 per maximal invented run (Line2 has no per-segment
 * colour; runs keep the geometry count at the gap count, not the point
 * count). Positions are COPIES of the line's draped positions — same
 * lattice, same drape, same frame. Returns the group + audit counts. */
export function buildGapsOverlay(
  linePositions: number[],
  route: RouteData,
  ranges: Array<readonly [number, number]>,
  resolution: THREE.Vector2,
): { group: THREE.Group; inventedM: number; inventedRuns: number } {
  const group = new THREE.Group();
  let inventedM = 0;
  let inventedRuns = 0;
  let run: number[] = [];
  const flush = (): void => {
    if (run.length < 6) {
      run = [];
      return;
    }
    inventedRuns++;
    const geo = new LineGeometry();
    geo.setPositions(run);
    const mat = new LineMaterial({
      color: MAGENTA,
      linewidth: 4.5,
      worldUnits: false,
      alphaToCoverage: false,
      transparent: true,
      opacity: 0.95,
      depthTest: true,
      depthWrite: false,
    });
    mat.resolution.copy(resolution);
    const l = new Line2(geo, mat);
    l.frustumCulled = false;
    l.renderOrder = 7;
    group.add(l);
    run = [];
  };
  // Point i is invented iff its along-track distance sits in a gap range.
  // A segment is invented iff BOTH endpoints are invented (never bleed
  // magenta past the gap edge onto genuine trace).
  // Returns a rebuild(positions) closure: the line redrapes on LOD change
  // (positions move), so the overlay re-copies them. Callers dispose the
  // old group children (geometry + material) before rebuilding.
  const n = route.n;
  const stepM = route.stepM > 0 ? route.stepM : 5;
  for (let i = 0; i < n - 1; i++) {
    const a = inventedAt(route.d[i] as number, ranges);
    const b = inventedAt(route.d[i + 1] as number, ranges);
    if (a && b) {
      if (run.length === 0) {
        run.push(
          linePositions[i * 3] as number,
          linePositions[i * 3 + 1] as number,
          linePositions[i * 3 + 2] as number,
        );
      }
      run.push(
        linePositions[(i + 1) * 3] as number,
        linePositions[(i + 1) * 3 + 1] as number,
        linePositions[(i + 1) * 3 + 2] as number,
      );
      inventedM += stepM;
    } else {
      flush();
    }
  }
  flush();
  return { group, inventedM, inventedRuns };
}
